name = "bridgebot"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
party = ">= 1.0.6 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
glenvy = ">= 2.0.0 and < 3.0.0"
discord_gleam = ">= 2.0.0 and < 3.0.0"
stdin = ">= 2.0.2 and < 3.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
birdie = ">= 1.2.7 and < 2.0.0"
unitest = ">= 1.1.0 and < 2.0.0"
